development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 10000

test:
  adapter: mysql2
  username: mas
  password: mas
  database: comfy_test
  encoding: utf8
  host: database
  port: 3306
  pool: 5
  timeout: 5000