#!/bin/bash -l

set -e

if [ -f /.dockerenv ]; then
    source ~/.bashrc
    rvm use default
fi

export RAILS_ENV=test
export BUNDLE_WITHOUT=development:build

function run {
    declare -a tests_command=("$@")

    echo ''
    echo "=== Running \`${tests_command[*]}\`"
    if ! ${tests_command[*]}; then
        echo "=== These tests failed."
        exit 1
    fi
}

function info {
    declare -a info_command=("$@")
    echo ''
    echo "=== Running for informational purposes \`${info_command[*]}\`"
    if ! ${info_command[*]}; then
        echo "== This test has errors and/or warnings. Please review results"
    fi
}

run ls bundle/cache
run bundle install --path=vendor/cache
run bundle exec rake db:drop db:create db:migrate
run bundle exec rake test
info bundle exec brakeman -q --no-pager --ensure-latest

if [ -f /.dockerenv ]; then
  run bundle exec danger --dangerfile=jenkins/Dangerfile --verbose
fi
